name: C/C++ CI

on: [pull_request, push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild SSE2
      working-directory: Osiris
      run: msbuild Osiris_SSE2.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\SSE2\"
    - name: ls
      run: ls
    - name: MSBuild AVX
      working-directory: Osiris
      run: msbuild Osiris_AVX.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\AVX\"
    - name: ls
      run: ls
    - name: MSBuild AVX2
      working-directory: Osiris
      run: msbuild Osiris_AVX2.vcxproj /p:Configuration=Release /p:VisualStudioVersion=16.0 /v:m /p:OutDir="D:\a\Osiris\Osiris\Osiris\Release\AVX2\"
    - uses: actions/upload-artifact@v1
      with:
        name: Release SSE2
        path: Osiris/Release/SSE2/Osiris_SSE2.dll
    - uses: actions/upload-artifact@v1
      with:
        name: Release AVX
        path: Osiris/Release/AVX/Osiris_AVX.dll
    - uses: actions/upload-artifact@v1
      with:
        name: Release AVX2
        path: Osiris/Release/AVX2/Osiris_AVX2.dll
